#!/bin/bash
# Autor: Robson Vaamonde
# Site: www.procedimentosemti.com.br
# Facebook: facebook.com/ProcedimentosEmTI
# Facebook: facebook.com/BoraParaPratica
# YouTube: youtube.com/BoraParaPratica
# Data de criação: 31/05/2016
# Data de atualização: 17/12/2016
# Versão: 0.4
# Testado e homologado para a versão do Ubuntu Server 16.04 LTS x64
# Kernel >= 4.4.x
#
# Criando as váriaveis de validação do diretório
LOG="/var/log/cups/log.limpeza_cups"
SPOOL="/var/spool/cups"
LOGS="/var/log/cups"
CACHE="/var/cache/cups"

#Parando o serviço do CUPS
sudo service cups stop > $LOG

cd $SPOOL
LOCAL1="`pwd`"
#Fazendo o teste lógico para a limpeza do diretório Spool
if [ $SPOOL == $LOCAL1 ]; then
	echo -e "Fazendo a limpeza do diretório: $SPOOL em: `date`" >> $LOG
	echo >> $LOG
		rm -Rfv * >> $LOG
	echo >> $LOG
	echo -e "Pasta $SPOOL limpa com sucesso!!!" >> $LOG
else
	echo -e "Diretório $SPOOL inexistente, verificar as configurações da váriavél de ambiente, localização dos arquivos, etc" >> $LOG
fi

cd $LOGS
LOCAL2="`pwd`"
#Fazendo o teste lógico para a limpeza do diretório Logs
if [ $LOGS == $LOCAL2 ]; then
	echo -e "Fazendo a limpeza do diretório: $LOGS em: `date`" >> $LOG
	echo >> $LOG
		rm -fv *_log* >> $LOG
	echo >> $LOG
	echo -e "Pasta $LOGS limpa com sucesso!!!" >> $LOG
else
	echo -e "Diretório $LOGS inexistente, verificar as configurações da váriavél de ambiente, localização dos arquivos, etc" >> $LOG
fi

cd $CACHE
LOCAL3="`pwd`"
#Fazendo o teste lógico para a limpeza do diretório Cache
if [ $CACHE == $LOCAL3 ]; then
	echo -e "Fazendo a limpeza do diretório: $CACHE em: `date`" >> $LOG
	echo >> $LOG
		rm -fv job.cache* *.data >> $LOG
	echo >> $LOG
	echo -e "Pasta $CACHE limpa com sucesso!!!" >> $LOG
else
	echo -e "Diretório $LOGS inexistente, verificar as configurações da váriavél de ambiente, localização dos arquivos, etc" >> $LOG
fi

#Iniciando o serviço do CUPS
sudo service cups start >> $LOG
