#!/bin/bash
# Autor: Robson Vaamonde
# Site: www.procedimentosemti.com.br
# Facebook: facebook.com/ProcedimentosEmTI
# Facebook: facebook.com/BoraParaPratica
# YouTube: youtube.com/BoraParaPratica
# Data de criação: 31/05/2016
# Data de atualização: 31/07/2016
# Versão: 0.4
# Testado e homologado para a versão do Ubuntu Server 16.04 LTS x64
# Kernel >= 4.4.x
#
# Criando as váriaveis de validação do diretório
LOG="/var/log/samba/log.limpeza_publico"
PUBLICO="/arquivos/pti.intra/publico"
cd $PUBLICO
LOCAL="`pwd`"

#Fazendo o teste lógico para a limpeza do diretório Público.
if [ $PUBLICO == $LOCAL ]; then
	echo -e "Fazendo a limpeza do diretório: $PUBLICO em: `date`" > $LOG
	echo >> $LOG
	rm -Rfv * >> $LOG
	echo >> $LOG
	echo -e "Pasta Publico limpada com sucesso!!!" >> $LOG
else
	echo -e "Diretório público inexistente, verificar as configurações da váriavél de ambiente, localização dos arquivos, etc" >> $LOG
fi