#!/bin/bash
# Autor: Robson Vaamonde
# Site: www.procedimentosemti.com.br
# Facebook: facebook.com/ProcedimentosEmTI
# Facebook: facebook.com/BoraParaPratica
# YouTube: youtube.com/BoraParaPratica
# Data de criação: 31/05/2016
# Data de atualização: 04/08/2016
# Versão: 0.4
# Testado e homologado para a versão do Ubuntu Server 16.04 LTS x64
# Kernel >= 4.4.x
#
# Opções do Rsync
# r = recursive
# a = archive
# v = verbose
# z = compress
# p = progress

ORIGEM="/arquivos/pti.intra/"
DESTINO="/backup/pti.intra/rsync"
LOG="/var/log/samba/log.rsync_samba"

rsync -Cravzp $ORIGEM $DESTINO > $LOG