#!/bin/sh
# Criado por: Matthieu Patou
# Site: https://goo.gl/PAamQV
# Modificador por: Robson Vaamonde
# Site: www.procedimentosemti.com.br
# Facebook: facebook.com/ProcedimentosEmTI
# Facebook: facebook.com/BoraParaPratica
# YouTube: youtube.com/BoraParaPratica
# Data de criação: 31/05/2016
# Data de atualização: 03/01/2017
# Versão: 0.8
# Testado e homologado para a versão do Ubuntu Server 16.04 LTS x64
# Kernel >= 4.4.x

#Criação das variáveis para o backup
FROMWHERE=/var/lib/samba
WHERE=/backup/samba4
DAYS=90				# Set default retention period.
LOG=/var/log/samba/log.samba_backup

#
if [ -n "$1" ] && [ "$1" = "-h" -o "$1" = "--usage" ]; then
	echo "samba_backup [provisiondir] [destinationdir] [retpd]"
	echo "Will backup your provision located in provisiondir to archive stored"
	echo "in destinationdir for retpd days. Use - to leave an option unchanged."
	echo "Default provisiondir: $FROMWHERE"
	echo "Default destinationdir: $WHERE"
	echo "Default destinationdir: $DAYS"
	exit 0
fi

#
[ -n "$1" -a "$1" != "-" ]&&FROMWHERE=$1	# Use parm or default if "-".  Validate later.
[ -n "$2" -a "$2" != "-" ]&&WHERE=$2		# Use parm or default if "-".  Validate later.
[ -n "$3" -a "$3" -eq "$3" 2> /dev/null ]&&DAYS=$3	# Use parm or default if non-numeric (incl "-").

#Criação da estrutura de LOG
echo -e "Iniciando o Backup do SAMBA em: `date`" > $LOG
echo >> $LOG

# Atualização do diretório /etc/samba no caminho /var/lib/samba/etc
# Melhoria da copia de arquivos com a opção -v e saida para o LOG
cp -Rfv /etc/samba/* /var/lib/samba/etc/ >> $LOG

# Diretórios que serão feitos os backups
DIRS="private etc sysvol"

#Number of days to keep the backup
WHEN=`date +%Y-%m-%d`	# ISO 8601 standard date.

if [ ! -d $WHERE ]; then
	echo "Missing backup directory $WHERE" >> $LOG
	exit 1
fi

if [ ! -d $FROMWHERE ]; then
	echo "Missing or wrong provision directory $FROMWHERE" >> $LOG
	exit 1
fi

cd $FROMWHERE
for d in $DIRS;do
	relativedirname=`find . -type d -name "$d" -prune`
	n=`echo $d | sed 's/\//_/g'`
	if [ "$d" = "private" ]; then
		# Melhoria da remoção de arquivos com a opção -v e saida para o LOG
		find $relativedirname -name "*.ldb.bak" -exec rm -v {} \; >> $LOG
		for ldb in `find $relativedirname -name "*.ldb"`; do
			tdbbackup $ldb
			Status=$?	# Preserve $? for message, since [ alters it.
			if [ $Status -ne 0 ]; then
				echo "Error while backing up $ldb - status $Status" >> $LOG
				exit 1
			fi
		done
		# Run the backup.
		#    --warning=no-file-ignored set to suppress "socket ignored" messages.
		# Acrescimento da opção: -v e saida para o LOG
		tar cjfv ${WHERE}/samba4_${n}.${WHEN}.tar.bz2  $relativedirname --exclude=\*.ldb --warning=no-file-ignored --transform 's/.ldb.bak$/.ldb/' >> $LOG
		Status=$?	# Preserve $? for message, since [ alters it.
		if [ $Status -ne 0 -a $Status -ne 1 ]; then	# Ignore 1 - private dir is always changing.
			echo "Error while archiving ${WHERE}/samba4_${n}.${WHEN}.tar.bz2 - status = $Status" >> $LOG
			exit 1
		fi
		# Melhoria da remoção de arquivos com a opção -v e saida para o LOG
		find $relativedirname -name "*.ldb.bak" -exec rm -v {} \; >> $LOG
	else
		# Run the backup.
		#    --warning=no-file-ignored set to suppress "socket ignored" messages.
		# Acrescimento da opção: -v e saida para o LOG
		tar cjfv ${WHERE}/${n}.${WHEN}.tar.bz2  $relativedirname --warning=no-file-ignored >> $LOG
		Status=$?	# Preserve $? for message, since [ alters it.
		if [ $Status -ne 0 ]; then
			echo "Error while archiving ${WHERE}/${n}.${WHEN}.tar.bz2 - status = $Status" >> $LOG
			exit 1
		fi
	fi
done
# Melhoria da remoção de arquivos com a opção -v e saida para o LOG
find $WHERE -name "samba4_*bz2" -mtime +$DAYS -exec rm -v {} \; >> $LOG

echo -e "Fim do Backup do SAMBA em: `date`" >> $LOG
